name: benchmark-data-leakage

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.10
  - rdkit
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - jupyterlab
  - tqdm
  - psycopg2
  - bioconda::mmseqs2